=== jesusmgc1996/LMSGI_Ejercicios/DTD/examenamigos.dtd
<!ELEMENT amigos (#PCDATA | amigo | amiga)*>
<!ELEMENT amigo (apellido, independizado?, (edad | fechaCumpleanios)+)>
<!ELEMENT amiga (apellido, independizado?, (edad | fechaCumpleanios)+)>
<!ELEMENT apellido (#PCDATA)>
<!ELEMENT independizado EMPTY>
<!ELEMENT edad (#PCDATA)>
<!ELEMENT fechaCumpleanios (#PCDATA)>
<!ENTITY % atributos "nombre ID #REQUIRED
                        localidad (lucena | malaga | cordoba) 'lucena'
                        amigode IDREFS #IMPLIED
                        parejade IDREF #IMPLIED
                        casado NMTOKEN #FIXED 'si'">
<!ATTLIST amigo %atributos;>
<!ATTLIST amiga %atributos;>

=== jesusmgc1996/LMSGI_Ejercicios/DTD/examenamigos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE amigos SYSTEM "examenamigos.dtd">
<amigos>Lista de amigos
	<amigo nombre="Pepe" localidad="lucena" amigode="Pablo Sonia" parejade="Laura" casado="si">
		<apellido>Jiménez</apellido>
		<independizado/>
        <fechaCumpleanios>8 de mayo</fechaCumpleanios>
    </amigo>
    <amigo nombre="Pablo" localidad="malaga" amigode="Pepe Laura">
		<apellido>Pérez</apellido>
		<edad>27</edad>
    </amigo>
	<amiga nombre="Laura" localidad="cordoba" amigode="Pablo Sonia" parejade="Pepe" casado="si">
		<apellido>García</apellido>
		<independizado/>
		<edad>26</edad>
        <fechaCumpleanios>19 de octubre</fechaCumpleanios>
    </amiga>
    <amiga nombre="Sonia" localidad="cordoba" amigode="Laura">
		<apellido>García</apellido>
		<independizado/>
		<edad>25</edad>
    </amiga>
</amigos>
